import {
	create,
	end,
	get,
	getEmbedAgent,
	getTrialLink,
	list,
	patchLifecycle,
	postEvent,
	postReport,
	postToolCall,
	startEgressInternal,
	startEmbedSession,
	startSessionEgress,
	startTrialSession,
	uploadFileInternal,
	uploadParticipantFile,
	warmEmbedSpatialRealCredentials,
	warmSpatialRealCredentials,
	warmTrialSpatialRealCredentials,
} from "./procedures";

export const sessionsRouter = {
	list,
	get,
	create,
	end,
	getTrialLink,
	startTrialSession,
	warmTrialSpatialRealCredentials,
	getEmbedAgent,
	startEmbedSession,
	warmEmbedSpatialRealCredentials,
	warmSpatialRealCredentials,
	uploadParticipantFile,
	startEgress: startSessionEgress,
	internal: {
		patchLifecycle,
		postEvent,
		postToolCall,
		postReport,
		startEgress: startEgressInternal,
		uploadFile: uploadFileInternal,
	},
};
