import {
	assignNumber,
	createDispatch,
	createVoice,
	deleteRule,
	deleteTrunk,
	listEgressJobsProc,
	listNumbers,
	listRules,
	listTrunks,
	listVoices,
	mintToken,
	provisionInboundSip,
	provisionOutboundSip,
	startEgress,
	startOutbound,
	stopEgressJob,
	syncPlivoNumbers,
} from "./procedures";

export const telephonyRouter = {
	listNumbers,
	syncPlivoNumbers,
	assignNumber,
	provisionInboundSip,
	provisionOutboundSip,
	listTrunks,
	deleteTrunk,
	createDispatch,
	listRules,
	deleteRule,
	createVoice,
	listVoices,
	mintToken,
	startOutbound,
	startEgress,
	stopEgressJob,
	listEgressJobs: listEgressJobsProc,
};
